---

- hosts: all
  become: true
  tasks:

  - name: install update (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 and php package for Ubuntu
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes      
    when: ansible_distribution == "Ubuntu"      

- hosts: web_servers
  become: true
  tasks:

  - name: install apache
    apt:
      name:
        - apache2
      state: latest
    
     

